# Generated by Django 2.2.16 on 2020-10-15 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('washescar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='galeriaImagenes',
            fields=[
                ('identificador', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('imagenGaleria', models.ImageField(null=True, upload_to='galeria')),
                ('mensaje', models.CharField(max_length=15)),
                ('overlay', models.CharField(max_length=15)),
            ],
        ),
    ]
