# Generated by Django 2.2.16 on 2020-10-20 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('washescar', '0004_auto_20201015_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='MisionVision',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('mision', models.TextField()),
                ('vision', models.TextField()),
            ],
        ),
    ]
