# Generated by Django 2.2.16 on 2020-10-23 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('washescar', '0005_misionvision'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=30)),
                ('precio', models.IntegerField()),
                ('descripcion', models.TextField(verbose_name=100)),
            ],
        ),
    ]
