# Generated by Django 2.2.16 on 2020-10-23 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('washescar', '0006_insumos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumos',
            name='precio',
            field=models.TextField(max_length=7),
        ),
    ]
