# Generated by Django 2.2.16 on 2020-10-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('washescar', '0007_auto_20201023_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumos',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='insumos',
            name='nombre',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='insumos',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
