# Generated by Django 2.2.16 on 2020-10-24 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('washescar', '0008_auto_20201023_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumos',
            name='stock',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
